apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    app: db
  strategy:
    activeDeadlineSeconds: 3600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    resources: {}
    type: Rolling
  template:
    metadata:
      name: db
      creationTimestamp: null
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              value: db
            - name: MYSQL_PASSWORD
              value: db
            - name: MYSQL_DATABASE
              value: db
            - name: ALP_DB_HOST
              value: db
            - name: USERS_DB_HOST
              value: db
            - name: DEFAULT_DB_PORT
              value: '3306'
          image: 'registry.access.redhat.com/rhscl/mysql-56-rhel7:latest'
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: pvc-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-claim
  test: false
  triggers:
    - imageChangeParams:
        containerNames:
          - mysql
        from:
          kind: ImageStreamTag
          name: 'mysql:latest'
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
